### PR TITLE
update for julia 0.6

### PR DESCRIPTION
**Pull request by bjarthur**
@tlnagy this is also needed for Gadfly

### CODE REVIEW

**Comment by bjarthur** [comment]
added travis testing, but i guess it won't actually run those test until after this is merged?

**Comment by tlnagy** [comment]
I flipped the switch here: https://travis-ci.org/profile/GiovineItalia it should start to build now

**Comment by tlnagy** [comment]
*after you make another commit

**Comment by bjarthur** [comment]
easier to close and reopen than to push an unneeded commit

**Pull request merged**
